diff --cc Dominio/.classpath
index f362f73,f362f73..0000000
mode 100755,100644..100755
--- a/Dominio/.classpath
+++ b/Dominio/.classpath
diff --cc Dominio/.project
index 041384d,041384d..0000000
mode 100755,100644..100755
--- a/Dominio/.project
+++ b/Dominio/.project
diff --cc Dominio/.settings/org.eclipse.core.resources.prefs
index f9fe345,f9fe345..0000000
mode 100755,100644..100755
--- a/Dominio/.settings/org.eclipse.core.resources.prefs
+++ b/Dominio/.settings/org.eclipse.core.resources.prefs
diff --cc Dominio/.settings/org.eclipse.jdt.core.prefs
index abec6ca,abec6ca..0000000
mode 100755,100644..100755
--- a/Dominio/.settings/org.eclipse.jdt.core.prefs
+++ b/Dominio/.settings/org.eclipse.jdt.core.prefs
diff --cc Dominio/.settings/org.eclipse.m2e.core.prefs
index f897a7f,f897a7f..0000000
mode 100755,100644..100755
--- a/Dominio/.settings/org.eclipse.m2e.core.prefs
+++ b/Dominio/.settings/org.eclipse.m2e.core.prefs
diff --cc Dominio/pom.xml
index 0ee25a9,ce15989..0000000
mode 100755,100644..100755
--- a/Dominio/pom.xml
+++ b/Dominio/pom.xml
@@@ -7,7 -7,9 +7,13 @@@
      <groupId>Raisingsoft</groupId>
      <version>0.0.1-SNAPSHOT</version>
    </parent>
++<<<<<<< HEAD
 +  <artifactId>Dominio</artifactId>
++=======
+   <groupId>Raisingsoft</groupId>
+   <artifactId>Dominio</artifactId>
+   <version>0.0.1-SNAPSHOT</version>
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
    <name>Dominio</name>
    <url>http://maven.apache.org</url>
    <properties>
diff --cc Dominio/src/main/java/org/Dominio/Banco.java
index d0daf3a,ad3d0f9..0000000
mode 100755,100644..100755
--- a/Dominio/src/main/java/org/Dominio/Banco.java
+++ b/Dominio/src/main/java/org/Dominio/Banco.java
@@@ -6,14 -6,18 +6,26 @@@ public class Banco 
  	
  	public Banco(int IdBanco, String Descripcion) {
  		super();
++<<<<<<< HEAD
 +		this.IdBanco=IdBanco;
 +		this.Descripcion=Descripcion;
++=======
+ 		this.setIdBanco(IdBanco);
+ 		this.setDescripcion(Descripcion);
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  	}
  
  	public int getIdBanco() {
  		return IdBanco;
  	}
  
++<<<<<<< HEAD
++=======
+ 	public void setIdBanco(int idBanco) {
+ 		IdBanco = idBanco;
+ 	}
+ 
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  	public String getDescripcion() {
  		return Descripcion;
  	}
diff --cc Dominio/src/main/java/org/Dominio/Beneficios.java
index 5829402,5829402..0000000
mode 100755,100644..100755
--- a/Dominio/src/main/java/org/Dominio/Beneficios.java
+++ b/Dominio/src/main/java/org/Dominio/Beneficios.java
diff --cc Dominio/src/main/java/org/Dominio/BocaPago.java
index 774eb13,774eb13..0000000
mode 100755,100644..100755
--- a/Dominio/src/main/java/org/Dominio/BocaPago.java
+++ b/Dominio/src/main/java/org/Dominio/BocaPago.java
diff --cc Dominio/src/main/java/org/Dominio/Presupuesto.java
index b85d4c9,b85d4c9..0000000
mode 100755,100644..100755
--- a/Dominio/src/main/java/org/Dominio/Presupuesto.java
+++ b/Dominio/src/main/java/org/Dominio/Presupuesto.java
diff --cc Dominio/src/test/java/org/Dominio/AppTest.java
index 2b66466,2b66466..0000000
mode 100755,100644..100755
--- a/Dominio/src/test/java/org/Dominio/AppTest.java
+++ b/Dominio/src/test/java/org/Dominio/AppTest.java
diff --cc Dominio/target/classes/META-INF/maven/Raisingsoft/Dominio/pom.properties
index 59b54ab,1756cac..0000000
--- a/Dominio/target/classes/META-INF/maven/Raisingsoft/Dominio/pom.properties
+++ b/Dominio/target/classes/META-INF/maven/Raisingsoft/Dominio/pom.properties
@@@ -1,5 -1,5 +1,9 @@@
  #Generated by Maven Integration for Eclipse
++<<<<<<< HEAD
 +#Thu Apr 12 16:45:38 PDT 2012
++=======
+ #Sun Apr 08 16:59:18 PDT 2012
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  version=0.0.1-SNAPSHOT
  groupId=Raisingsoft
  m2e.projectName=Dominio
diff --cc Dominio/target/classes/META-INF/maven/Raisingsoft/Dominio/pom.xml
index 0ee25a9,ce15989..0000000
--- a/Dominio/target/classes/META-INF/maven/Raisingsoft/Dominio/pom.xml
+++ b/Dominio/target/classes/META-INF/maven/Raisingsoft/Dominio/pom.xml
@@@ -7,7 -7,9 +7,13 @@@
      <groupId>Raisingsoft</groupId>
      <version>0.0.1-SNAPSHOT</version>
    </parent>
++<<<<<<< HEAD
 +  <artifactId>Dominio</artifactId>
++=======
+   <groupId>Raisingsoft</groupId>
+   <artifactId>Dominio</artifactId>
+   <version>0.0.1-SNAPSHOT</version>
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
    <name>Dominio</name>
    <url>http://maven.apache.org</url>
    <properties>
diff --cc Dominio/target/classes/org/Dominio/Banco.class
index 9ee4fea,a84a434..0000000
--- a/Dominio/target/classes/org/Dominio/Banco.class
+++ b/Dominio/target/classes/org/Dominio/Banco.class
diff --cc Persistencia/.classpath
index b0a6333,4d33102..0000000
mode 100755,100644..100755
--- a/Persistencia/.classpath
+++ b/Persistencia/.classpath
@@@ -2,7 -2,7 +2,11 @@@
  <classpath>
  	<classpathentry kind="src" output="target/classes" path="src/main/java"/>
  	<classpathentry kind="src" output="target/test-classes" path="src/test/java"/>
++<<<<<<< HEAD
 +	<classpathentry kind="src" path="src/main/resources"/>
++=======
+ 	<classpathentry kind="src" path="src/main/resource"/>
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/J2SE-1.5"/>
  	<classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER"/>
  	<classpathentry kind="src" path="/Dominio"/>
diff --cc Persistencia/.project
index b66da38,b66da38..0000000
mode 100755,100644..100755
--- a/Persistencia/.project
+++ b/Persistencia/.project
diff --cc Persistencia/.settings/org.eclipse.core.resources.prefs
index f9fe345,f9fe345..0000000
mode 100755,100644..100755
--- a/Persistencia/.settings/org.eclipse.core.resources.prefs
+++ b/Persistencia/.settings/org.eclipse.core.resources.prefs
diff --cc Persistencia/.settings/org.eclipse.jdt.core.prefs
index abec6ca,abec6ca..0000000
mode 100755,100644..100755
--- a/Persistencia/.settings/org.eclipse.jdt.core.prefs
+++ b/Persistencia/.settings/org.eclipse.jdt.core.prefs
diff --cc Persistencia/.settings/org.eclipse.m2e.core.prefs
index f897a7f,f897a7f..0000000
mode 100755,100644..100755
--- a/Persistencia/.settings/org.eclipse.m2e.core.prefs
+++ b/Persistencia/.settings/org.eclipse.m2e.core.prefs
diff --cc Persistencia/pom.xml
index e09ea85,0b1f9f8..0000000
mode 100755,100644..100755
--- a/Persistencia/pom.xml
+++ b/Persistencia/pom.xml
@@@ -7,7 -7,9 +7,13 @@@
      <groupId>Raisingsoft</groupId>
      <version>0.0.1-SNAPSHOT</version>
    </parent>
++<<<<<<< HEAD
 +  <artifactId>Persistencia</artifactId>
++=======
+   <groupId>Raisingsoft</groupId>
+   <artifactId>Persistencia</artifactId>
+   <version>0.0.1-SNAPSHOT</version>
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
    <name>Persistencia</name>
    <url>http://maven.apache.org</url>
    <properties>
diff --cc Persistencia/src/main/java/org/Persistencia/Abstract.java
index d5d48e0,49253be..0000000
mode 100755,100644..100755
--- a/Persistencia/src/main/java/org/Persistencia/Abstract.java
+++ b/Persistencia/src/main/java/org/Persistencia/Abstract.java
@@@ -6,12 -6,9 +6,18 @@@ import java.sql.DriverManager
  import java.sql.SQLException;
  import java.util.Properties;
  import java.util.ServiceLoader;
++<<<<<<< HEAD
 +//import java.io.Console;
  
  public abstract class Abstract {
  	
 +	//private Console console;
 +	
++=======
++
++public abstract class Abstract {
++	
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  	private final ThreadLocal<Connection> THREAD_CONNECTION = new ThreadLocal<Connection>();
  	private final Properties propiedades;
  	// Tipo de motor
@@@ -42,15 -39,6 +48,18 @@@
  			base = propiedades.getProperty("jdbc.base");
  			user = propiedades.getProperty("jdbc.user");
  			password = propiedades.getProperty("jdbc.password");
++<<<<<<< HEAD
 +			//if(MOTOR == null)
 +			//{
 +				//console.printf("No anda");
 +			//}
 +			//else
 +			//{
 +				//console.printf(MOTOR);	
 +			//}
 +			
++=======
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  		} catch (IOException ex) {
  			throw new RuntimeException(
  					"Falló lectura de archivo de configuracion", ex);
@@@ -122,9 -110,5 +131,12 @@@
  	protected abstract String getDriver();
  
  	protected abstract String getMotor();
++<<<<<<< HEAD
 +	
 +	/* Repositorios */
 +	public abstract IRepo_CtaCte getRepo_CtaCte() 
 +			throws RepositorioException;
++=======
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  
  }
diff --cc Persistencia/src/main/java/org/Persistencia/IRepo_CtaCte.java
index 31a32c0,eeaa605..0000000
mode 100755,100644..100755
--- a/Persistencia/src/main/java/org/Persistencia/IRepo_CtaCte.java
+++ b/Persistencia/src/main/java/org/Persistencia/IRepo_CtaCte.java
@@@ -1,8 -1,6 +1,13 @@@
  package org.Persistencia;
++<<<<<<< HEAD
 +
 +import org.Dominio.Banco;
 +
 +
++=======
+ import org.Dominio.Banco;
+ 
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  public interface IRepo_CtaCte {
  	/**
  	 * Agrega un objeto banco al medio persistente
diff --cc Persistencia/src/main/java/org/Persistencia/RepositorioException.java
index 98fa3f7,98fa3f7..0000000
mode 100755,100644..100755
--- a/Persistencia/src/main/java/org/Persistencia/RepositorioException.java
+++ b/Persistencia/src/main/java/org/Persistencia/RepositorioException.java
diff --cc Persistencia/src/main/java/org/PostreSql/PostgreSqlDB.java
index ea8f247,c9858d5..0000000
mode 100755,100644..100755
--- a/Persistencia/src/main/java/org/PostreSql/PostgreSqlDB.java
+++ b/Persistencia/src/main/java/org/PostreSql/PostgreSqlDB.java
@@@ -1,42 -1,13 +1,56 @@@
  package org.PostreSql;
  
++<<<<<<< HEAD
 +import org.Persistencia.Abstract;
 +import org.Persistencia.IRepo_CtaCte;
 +import org.Persistencia.RepositorioException;
 +import java.io.Console;
 +
 +public final class PostgreSqlDB extends Abstract {
 +	
 +	private Console console;
 +	
 +	/* ====== ImplementaciÃ³n de repositorios ====== */
 +	@Override
 +	public IRepo_CtaCte getRepo_CtaCte()
 +			throws RepositorioException {
 +		return new Repo_Pg_CtaCte(getConnection());
 +	}
 +	
 +	//@Override
 +	//public IPersonaRepositorio getPersonaRepositorio()
 +		//	throws RepositorioException {
 +		//return new PersonaPgRepositorio(getConnection());
 +	//}
 +
 +	/* ====== ImplementaciÃ³n metodos template ====== */
 +	@Override
 +	protected String getUrl(String servidor, String base) {
 +		console.printf("servidor:" + servidor);
 +		return "jdbc:postgresql://" + servidor + "/" + base;
 +	}
 +
 +	@Override
 +	protected String getDriver() {
 +		return "org.postgresql.Driver";
 +	}
 +
 +	@Override
 +	protected String getMotor() {
 +		return "postgresql";
 +	}
 +}
 +
++=======
+ import java.sql.Connection;
+ 
+ import org.Dominio.Banco;
+ import org.Persistencia.RepositorioException;
+ import org.Persistencia.IRepo_CtaCte;
+ 
+ 
+ public class PostgreSqlDB implements IRepo_CtaCte {
+ 	private Connection connection;
+ 
+ }
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
diff --cc Persistencia/src/test/java/org/Persistencia/AppTest.java
index aee7a35,aee7a35..0000000
mode 100755,100644..100755
--- a/Persistencia/src/test/java/org/Persistencia/AppTest.java
+++ b/Persistencia/src/test/java/org/Persistencia/AppTest.java
diff --cc Persistencia/target/classes/META-INF/maven/Raisingsoft/Persistencia/pom.properties
index 0544d9f,1d6ef48..0000000
--- a/Persistencia/target/classes/META-INF/maven/Raisingsoft/Persistencia/pom.properties
+++ b/Persistencia/target/classes/META-INF/maven/Raisingsoft/Persistencia/pom.properties
@@@ -1,5 -1,5 +1,9 @@@
  #Generated by Maven Integration for Eclipse
++<<<<<<< HEAD
 +#Thu Apr 12 17:35:00 PDT 2012
++=======
+ #Tue Apr 10 18:03:43 PDT 2012
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
  version=0.0.1-SNAPSHOT
  groupId=Raisingsoft
  m2e.projectName=Persistencia
diff --cc Persistencia/target/classes/META-INF/maven/Raisingsoft/Persistencia/pom.xml
index e09ea85,0b1f9f8..0000000
--- a/Persistencia/target/classes/META-INF/maven/Raisingsoft/Persistencia/pom.xml
+++ b/Persistencia/target/classes/META-INF/maven/Raisingsoft/Persistencia/pom.xml
@@@ -7,7 -7,9 +7,13 @@@
      <groupId>Raisingsoft</groupId>
      <version>0.0.1-SNAPSHOT</version>
    </parent>
++<<<<<<< HEAD
 +  <artifactId>Persistencia</artifactId>
++=======
+   <groupId>Raisingsoft</groupId>
+   <artifactId>Persistencia</artifactId>
+   <version>0.0.1-SNAPSHOT</version>
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
    <name>Persistencia</name>
    <url>http://maven.apache.org</url>
    <properties>
diff --cc Persistencia/target/classes/jdbc.properties
index 1d6c852,1d6c852..0000000
mode 100755,100644..100755
--- a/Persistencia/target/classes/jdbc.properties
+++ b/Persistencia/target/classes/jdbc.properties
diff --cc Persistencia/target/classes/org/Persistencia/Abstract.class
index cc50bb6,96dc876..0000000
--- a/Persistencia/target/classes/org/Persistencia/Abstract.class
+++ b/Persistencia/target/classes/org/Persistencia/Abstract.class
diff --cc Persistencia/target/classes/org/PostreSql/PostgreSqlDB.class
index 85ea6d9,3f27567..0000000
--- a/Persistencia/target/classes/org/PostreSql/PostgreSqlDB.class
+++ b/Persistencia/target/classes/org/PostreSql/PostgreSqlDB.class
diff --cc pom.xml
index fe6145d,56c50f0..0000000
mode 100755,100644..100755
--- a/pom.xml
+++ b/pom.xml
@@@ -10,7 -10,5 +10,10 @@@
    <modules>
      <module>Dominio</module>
      <module>Persistencia</module>
++<<<<<<< HEAD
 +    <module>Servicios</module>
 +    <module>ui</module>
++=======
++>>>>>>> a2f3759e12b710ebf4df6c9d1077eacb574e90d0
    </modules>
  </project>
diff --git a/ui/src/main/java/org/ui/App.java b/ui/src/main/java/org/ui/App.java
deleted file mode 100644
index 1bca219..0000000
--- a/ui/src/main/java/org/ui/App.java
+++ /dev/null
@@ -1,13 +0,0 @@
-package org.ui;
-
-/**
- * Hello world!
- *
- */
-public class App 
-{
-    public static void main( String[] args )
-    {
-        System.out.println( "Hello World!" );
-    }
-}
diff --git a/ui/target/classes/org/ui/App.class b/ui/target/classes/org/ui/App.class
deleted file mode 100644
index 5713ba9..0000000
Binary files a/ui/target/classes/org/ui/App.class and /dev/null differ
